// Mock data for testing without backend

export const mockUsers = [
  {
    id: 'user-1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+91 98765 12345',
    orders: 14,
    joined: '2024-02-10',
    status: 'Active',
    avatarColor: '#3498db'
  },
  {
    id: 'user-2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '+91 99887 44556',
    orders: 8,
    joined: '2024-05-18',
    status: 'Active',
    avatarColor: '#e74c3c'
  },
  {
    id: 'user-3',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    phone: '+91 91234 56789',
    orders: 5,
    joined: '2025-01-12',
    status: 'Pending',
    avatarColor: '#2ecc71'
  },
  {
    id: 'user-4',
    name: 'Bob Williams',
    email: 'bob@example.com',
    phone: '+91 97654 33221',
    orders: 21,
    joined: '2023-10-09',
    status: 'Active',
    avatarColor: '#9b59b6'
  },
  {
    id: 'user-5',
    name: 'Michael Brown',
    email: 'michael@example.com',
    phone: '+91 90909 22334',
    orders: 11,
    joined: '2024-08-25',
    status: 'Active',
    avatarColor: '#f39c12'
  }
]

export const mockOrders = [
  {
    id: 'ORD-1001',
    customer: 'John Doe',
    customerId: 'user-1',
    items: '5',
    total: '850',
    payment: 'UPI',
    date: '2026-07-04',
    status: 'Delivered'
  },
  {
    id: 'ORD-1002',
    customer: 'Jane Smith',
    customerId: 'user-2',
    items: '5',
    total: '578',
    payment: 'COD',
    date: '2026-07-04',
    status: 'Pending'
  },
  {
    id: 'ORD-1003',
    customer: 'Alice Johnson',
    customerId: 'user-3',
    items: '5',
    total: '1150',
    payment: 'Card',
    date: '2026-07-03',
    status: 'Shipped'
  },
  {
    id: 'ORD-1004',
    customer: 'Bob Williams',
    customerId: 'user-4',
    items: '5',
    total: '1145',
    payment: 'UPI',
    date: '2026-07-03',
    status: 'Processing'
  },
  {
    id: 'ORD-1005',
    customer: 'Michael Brown',
    customerId: 'user-5',
    items: '5',
    total: '1524',
    payment: 'COD',
    date: '2026-07-02',
    status: 'Delivered'
  }
]

export const mockProducts = [
  {
    id: '#101',
    name: 'Fortune Basmati Rice',
    brand: 'FORTUNE',
    category: 'Grains',
    price: '110',
    description: 'Premium long grain basmati rice.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=200&h=200&fit=crop',
    productType: 'Aged Basmati Rice',
    modelName: '-',
    ingredients: '100% Basmati Rice',
    usedFor: 'Biryani, Pulao',
    unit: '1 kg',
    packagingType: 'Plastic Bag',
    storageInstruction: 'Store in a cool dry place',
    weight: '1 kg',
    disclaimer: 'Actual packaging may vary.',
    manufacturer: 'Fortune Foods Pvt. Ltd.',
    countryOfOrigin: 'India',
    shelfLife: '24 Months'
  },
  {
    id: '#102',
    name: 'Aashirvaad Atta',
    brand: 'AASHIRVAAD',
    category: 'Grains',
    price: '299',
    description: 'Whole wheat flour for soft rotis.',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=200&h=200&fit=crop',
    productType: 'Whole Wheat Flour',
    modelName: '-',
    ingredients: 'Whole Wheat',
    usedFor: 'Chapati, Paratha',
    unit: '5 kg',
    packagingType: 'Bag',
    storageInstruction: 'Keep airtight',
    weight: '5 kg',
    disclaimer: 'Actual packaging may vary.',
    manufacturer: 'ITC Ltd.',
    countryOfOrigin: 'India',
    shelfLife: '6 Months'
  },
  {
    id: '#103',
    name: 'Toor Dal',
    brand: 'TATA SAMPANN',
    category: 'Grains',
    price: '145',
    description: 'Protein rich premium toor dal.',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=200&h=200&fit=crop',
    productType: 'Pigeon Peas',
    modelName: '-',
    ingredients: '100% Toor Dal',
    usedFor: 'Dal, Curry',
    unit: '1 kg',
    packagingType: 'Plastic Bag',
    storageInstruction: 'Store dry',
    weight: '1 kg',
    disclaimer: 'Actual packaging may vary.',
    manufacturer: 'Tata Consumer Products',
    countryOfOrigin: 'India',
    shelfLife: '12 Months'
  },
  {
    id: '#104',
    name: 'MAGGI Noodles',
    brand: 'MAGGI',
    category: 'Snacks',
    price: '14',
    description: '2-minute instant noodles.',
    image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=200&h=200&fit=crop',
    productType: 'Instant Noodles',
    modelName: '-',
    ingredients: 'Wheat Flour, Spices',
    usedFor: 'Snacks',
    unit: '70 g',
    packagingType: 'Packet',
    storageInstruction: 'Store in cool dry place',
    weight: '70 g',
    disclaimer: 'Actual packaging may vary.',
    manufacturer: 'Nestle India',
    countryOfOrigin: 'India',
    shelfLife: '9 Months'
  },
  {
    id: '#105',
    name: 'Lay’s Classic Chips',
    brand: 'LAYS',
    category: 'Chips',
    price: '20',
    description: 'Classic salted potato chips.',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=200&h=200&fit=crop',
    productType: 'Potato Chips',
    modelName: '-',
    ingredients: 'Potatoes, Oil, Salt',
    usedFor: 'Snacking',
    unit: '52 g',
    packagingType: 'Packet',
    storageInstruction: 'Store in cool dry place',
    weight: '52 g',
    disclaimer: 'Actual packaging may vary.',
    manufacturer: 'PepsiCo India',
    countryOfOrigin: 'India',
    shelfLife: '6 Months'
  },
  {
    id: '#106',
    name: 'Coca-Cola Soft Drink',
    brand: 'COCA-COLA',
    category: 'Drinks',
    price: '95',
    description: 'Refreshing cold drink bottle.',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=200&h=200&fit=crop',
    productType: 'Soft Drink',
    modelName: '-',
    ingredients: 'Carbonated Water, Sugar',
    usedFor: 'Beverages',
    unit: '2 L',
    packagingType: 'Bottle',
    storageInstruction: 'Keep refrigerated',
    weight: '2 L',
    disclaimer: 'Actual packaging may vary.',
    manufacturer: 'Coca-Cola India',
    countryOfOrigin: 'India',
    shelfLife: '4 Months'
  },
  {
    id: '#107',
    name: 'Fresh Tomatoes',
    brand: 'FRESH FARM',
    category: 'Vegetables',
    price: '45',
    description: 'Fresh farm tomatoes.',
    image: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=200&h=200&fit=crop',
    productType: 'Vegetable',
    modelName: '-',
    ingredients: 'Tomato',
    usedFor: 'Cooking, Salad',
    unit: '1 kg',
    packagingType: 'Loose',
    storageInstruction: 'Keep refrigerated',
    weight: '1 kg',
    disclaimer: 'Fresh produce may vary in size.',
    manufacturer: 'Fresh Farm',
    countryOfOrigin: 'India',
    shelfLife: '5 Days'
  },
  {
    id: '#108',
    name: 'Fresh Bananas',
    brand: 'FRESH FARM',
    category: 'Fruits',
    price: '48',
    description: 'Naturally sweet bananas.',
    image: 'https://images.unsplash.com/photo-1574226516831-e1dff420e37f?w=200&h=200&fit=crop',
    productType: 'Fruit',
    modelName: '-',
    ingredients: 'Banana',
    usedFor: 'Snacks, Smoothies',
    unit: '1 dozen',
    packagingType: 'Loose',
    storageInstruction: 'Store at room temperature',
    weight: '1 dozen',
    disclaimer: 'Fresh produce may vary in size.',
    manufacturer: 'Fresh Farm',
    countryOfOrigin: 'India',
    shelfLife: '4 Days'
  }
]